stages:
  - install
  - type-check
  - lint
  - test
  - build
  - e2e
  - package

default:
  image: node:lts
  before_script:
    - npm install

install-job:
  stage: install
  tags:
    - elevation-app
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull-push
  script:
    - npm install

type-check-job:
  stage: type-check
  tags:
    - elevation-app
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull
  script:
    - npm run type-check

eslint-job:
  stage: lint
  tags:
    - elevation-app
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull
  script:
    - npm run lint

build-job:
  stage: build
  tags:
    - elevation-app
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull
  script:
    - npm run build

e2e-test-job:
  stage: e2e
  tags:
    - elevation-app
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull
  script:
    - cypress install
    - npm run ci

package-job:
  stage: package
  tags:
    - elevation-app
  script:
    - echo "Packging started..."
    - sleep 1
    - echo "Packging finished"
