// import { createAsyncThunk } from '@reduxjs/toolkit';
import { createSlice } from '@reduxjs/toolkit';
// import { AppThunk } from '../../app/store';
// import { fetchElevationData } from './elevationDataAPI';

// types
import type { RootState } from '../../app/store';
import type { PayloadAction } from '@reduxjs/toolkit';
import type { Location } from '../../types/schema';
import type { Map } from 'leaflet';

export interface ElevationDataState {
	location: Location;
	map: Map | null;
	elevation: number | null;
	status: 'idle' | 'loading' | 'failed';
}

const initialState: ElevationDataState = {
	location: { lat: 51.505, lng: -0.09 },
	elevation: null,
	map: null,
	status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
// export const incrementAsync = createAsyncThunk(
// 	'elevationData/fetchElevationData',
// 	async (amount: number) => {
// 		const response = await fetchElevationData(amount);
// 		// The value we return becomes the `fulfilled` action payload
// 		return response.data;
// 	},
// );

export const elevationDataSlice = createSlice({
	name: 'elevationData',
	initialState,
	// The `reducers` field lets us define reducers and generate associated actions
	reducers: {
		setLocation: (state, action: PayloadAction<Location>) => {
			state.location = action.payload;
		},
		setMap: (state, action: PayloadAction<Map>) => {
			state.map = action.payload;
		},
		setElevation: (state, action: PayloadAction<number>) => {
			state.elevation = action.payload;
		},
	},
	// The `extraReducers` field lets the slice handle actions defined elsewhere,
	// including actions generated by createAsyncThunk or in other slices.
	// extraReducers: (builder) => {
	// 	builder
	// 		.addCase(incrementAsync.pending, (state) => {
	// 			state.status = 'loading';
	// 		})
	// 		.addCase(incrementAsync.fulfilled, (state, action) => {
	// 			state.status = 'idle';
	// 			state.value += action.payload;
	// 		})
	// 		.addCase(incrementAsync.rejected, (state) => {
	// 			state.status = 'failed';
	// 		});
	// },
});

export const { setLocation, setMap, setElevation } = elevationDataSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.elevationData.value)`
export const selectLocation = (state: RootState) =>
	state.elevationData.location;

export const selectMap = (state: RootState) => state.elevationData.map;

export const selectElevation = (state: RootState) =>
	state.elevationData.elevation;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
// 	(amount: number): AppThunk =>
// 	(dispatch, getState) => {
// 		const currentValue = selectElevationData(getState());
// 		if (currentValue % 2 === 1) {
// 			dispatch(incrementByAmount(amount));
// 		}
// 	};

export default elevationDataSlice.reducer;
