import { createAsyncThunk } from '@reduxjs/toolkit';
import { createSlice } from '@reduxjs/toolkit';
import { fetchElevationData } from './elevationDataAPI';
// import { AppThunk } from '../../app/store';

// types
import type { RootState } from '../../app/store';
import type { PayloadAction } from '@reduxjs/toolkit';
import type { Location } from '../../types/schema';
import 'immer'; // Fix for error TS2742: The inferred type of 'elevationDataSlice' cannot be named without a reference to '.pnpm/immer@10.1.1/node_modules/immer'. This is likely not portable. A type annotation is necessary.

export interface ElevationDataState {
	location: Location;
	elevation: number | null;
	status: 'idle' | 'loading' | 'failed';
}

const initialState: ElevationDataState = {
	location: { lat: 51.505, lng: -0.09 },
	elevation: null,
	status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchElevationDataAsync = createAsyncThunk(
	'elevationData/fetchElevationData',
	async (location: Location, { rejectWithValue }) => {
		try {
			const response = await fetchElevationData(location);

			if (!response.ok) {
				return rejectWithValue(`HTTP error! Status: ${response.status}`);
			}

			const data = await response.json();

			if (
				data.results &&
				data.results[0] &&
				typeof data.results[0].elevation === 'number'
			) {
				const elevationData: number = data.results[0].elevation;
				return elevationData;
			} else {
				return rejectWithValue('Unexpected data format');
			}
		} catch (error: unknown) {
			if (error instanceof Error) {
				console.error('Fetch error:', error.message);
				return rejectWithValue(error.message);
			} else {
				console.error('Unexpected error:', error);
				return rejectWithValue('An unexpected error occurred');
			}
		}
	},
);

export const elevationDataSlice = createSlice({
	name: 'elevationData',
	initialState,
	// The `reducers` field lets us define reducers and generate associated actions
	reducers: {
		setLocation: (state, action: PayloadAction<Location>) => {
			state.location = action.payload;
		},
		setElevation: (state, action: PayloadAction<number>) => {
			state.elevation = action.payload;
		},
	},
	// The `extraReducers` field lets the slice handle actions defined elsewhere,
	// including actions generated by createAsyncThunk or in other slices.
	extraReducers: (builder) => {
		builder
			.addCase(fetchElevationDataAsync.pending, (state) => {
				state.status = 'loading';
			})
			.addCase(fetchElevationDataAsync.fulfilled, (state, action) => {
				state.status = 'idle';
				state.elevation = action.payload;
			})
			.addCase(fetchElevationDataAsync.rejected, (state) => {
				state.status = 'failed';
			});
	},
});

export const { setLocation, setElevation } = elevationDataSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.elevationData.value)`
export const selectLocation = (state: RootState) =>
	state.elevationData.location;

export const selectElevation = (state: RootState) =>
	state.elevationData.elevation;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
// 	(amount: number): AppThunk =>
// 	(dispatch, getState) => {
// 		const currentValue = selectElevationData(getState());
// 		if (currentValue % 2 === 1) {
// 			dispatch(incrementByAmount(amount));
// 		}
// 	};

export default elevationDataSlice.reducer;
